FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 5100
ENV ASPNETCORE_URLS=http://+:5100
COPY schoolinfo-api-publish/ .
RUN chmod -R 755 /app
ENTRYPOINT ["dotnet", "SchoolInfo.API.dll"]
